version: '3.9'

services:
  db:
    image: mysql:5.7
    ports:
    - 3307:3306
    volumes:
    - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
    - video-platform
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
    - ./../backend/:/var/www/video-platform/backend
    - ./php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
    - video-platform
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./nginx/nginx-local.conf:/etc/nginx/conf.d/default.conf
    - ./../frontend/:/var/www/video-platform/frontend
    - ./../backend/:/var/www/video-platform/backend
    - ./logs/nginx/:/var/log/nginx
    networks:
    - video-platform
networks:
  video-platform:
    driver: bridge
